#' Assess an R Package riskmetric with package name and version
#'
#' This function use `sanofi.risk.metric::assess_pkg` assessment function with only the package name and version
#'
#' @param package_name A character string specifying the name of the package to assess.
#' @param version A character string specifying the version of the package to assess. Default is `NA`, which assesses the latest version.
#'
#' @return The function returns a list of assessment results generated by the `sanofi.risk.metric::assess_pkg` function. 
#' If the package cannot be downloaded or installed, an error message is returned.
#'
#' @details This function follows these steps:
#' \enumerate{
#'   \item Downloads the specified R package using the `sanofi.risk.metric::get_tar_package` function.
#'   \item Installs the downloaded package in a temporary location.
#'   \item Runs the `sanofi.risk.metric::assess_pkg` function to assess the package for risks and issues.
#'   \item Returns the results of the assessment.
#' }
#'
#' @examples
#' \dontrun{
#' # Example usage of assess_pkg_r_package
#' results <- assess_pkg_r_package("here", version = "1.0.1")
#' print(results)
#' }
#'
#' @importFrom sanofi.risk.metric get_tar_package set_up_pkg assess_pkg
#' @importFrom utils download.file
#' @export
assess_pkg_r_package <- function(package_name, version=NA) {

  package_data <- sanofi.risk.metric::get_tar_package(package_name, version=version)
  
  if (is.null(package_data$error)) {
    package_url <- package_data$tar_link
  } else {
    return(package_data)
  }

  # Create a temporary file to store the downloaded package
  temp_file <- tempfile(fileext = ".tar.gz")

  tryCatch({
    download.file(package_url, temp_file, mode = "wb")
  }, error = function(e) {
    new_error_msg <- paste("Failed to download the package from the provided URL", package_data$tar_link, ". Error:", e$message)
    stop(new_error_msg, call. = FALSE)
  })
  
  modified_tar_file <- modify_description_file(temp_file, package_name)
  
  # Set up the package using the temporary file
  install_list <- sanofi.risk.metric::set_up_pkg(modified_tar_file)

    stop("Failed to download the package from the provided URL: ", package_url, ". Error: ", e$message)
  })
  
  # Set up the package using the temporary file
  install_list <- sanofi.risk.metric::set_up_pkg(temp_file)

  # Extract information from the installation list
  build_vignettes <- install_list$build_vignettes
  package_installed <- install_list$package_installed
  pkg_source_path <- install_list$pkg_source_path
  rcmdcheck_args <- install_list$rcmdcheck_args

  # Check if the package was installed successfully
  if (package_installed == TRUE) {
    # Assess the package
    assess_package <- sanofi.risk.metric::assess_pkg(pkg_source_path, rcmdcheck_args)
    # Output the assessment result
  } else {
    message("Package installation failed.")
  }

  # Clean up: remove the temporary file
  unlink(temp_file)
  return(assess_package)
}
