# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-coverage

permissions: write-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov, file = "coverage.xml")
          coverage_percentage <- round(covr::percent_coverage(cov), 0)
          writeLines(as.character(coverage_percentage), "coverage.txt")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
          
          
      - name: Create Shields.io badge URL
        id: create_badge
        run: |
          coverage=$(cat coverage.txt)
          if (( $(echo "${coverage} < 50" | bc -l) )); then
            color="red"
          elif (( $(echo "${coverage} < 80" | bc -l) )); then
            color="orange"
          else
            color="brightgreen"
          fi
          badge_url="<https://img.shields.io/badge/coverage-${coverage}%25-${color}.svg>"
          echo "badge_url=${badge_url}" >> $GITHUB_ENV
      
      - name: Update README with coverage badge
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b ${{ github.head_ref }}
          git pull --rebase origin ${{ github.head_ref }}
          sed -i 's|!\[Coverage\](https://img.shields.io/badge/coverage-[0-9]*%25-[a-z]*\.svg)|![Coverage]('"${{ env.badge_url }}"')|g' README.md
          git add README.md
          git commit -m 'Update README with coverage badge' || echo "No changes to commit"
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
          
          